// Yazı resimleri: Resim.yazı / yazıRenkli, yazıyüzü ve Font, dönüştürücü arkasındaki güncelle
// (kojojs-dev #19 bulgusu), çizMerkezdeYazı, kaplumbağa yazısı, yazıÇerçevesi.
sil(); artalanıKur(beyaz); yakınlaştırmayıKapat()
dez y1 = Resim.yazı("Merhaba Dünya", 24); çiz(götür(-300, 200) -> y1)
dez y2 = Resim.yazıRenkli("Renkli yazı: şğüöçİı", 20, kırmızı); çiz(götür(-300, 150) -> y2)
dez yy = yazıyüzü("serif", 30); dez y3 = Resim.yazı("Serif 30", yy, mavi); çiz(götür(-300, 100) -> y3)
dez y4 = Resim.yazı("Font(monospace, 18)", Font("monospace", 18), siyah); çiz(götür(-300, 50) -> y4)
dez y5 = Resim.yazı("kalın eğik", yazıyüzü("sans-serif", 22, Yazıyüzü.KALIN | Yazıyüzü.EĞİK), mor); çiz(götür(-300, 0) -> y5)
dez sayaç = götür(-300, -50) * büyüt(1.5) -> Resim.yazıRenkli("0", 20, yeşil)
çiz(sayaç)
sayaç.güncelle(42)
gerekli(sayaç.görünür, "yazı görünür olmalı")
dez doğrudan = Resim.yazıRenkli("sayaç", 18, koyuMavi); çiz(götür(100, -50) -> doğrudan); doğrudan.güncelle("sayaç: 7")
çizMerkezdeYazı("ortada", mor, 28)
yazıYüzünüKur(yazıyüzü("sans-serif", 16)); kalemRenginiKur(siyah); konumuKur(0, -150); yazı("kaplumbağa yazısı")
yazıBoyunuKur(22); konumuKur(0, -200); yazı("boy 22")
dez ç = yazıÇerçevesi("selam", 20)
gerekli(ç.eni > 0 && ç.boyu > 0, "yazı çerçevesi boş olmamalı: " + ç)
gerekli(yazıyüzleri.boyu > 3, "yazıyüzü listesi")
satıryaz("TAMAM: yazı")
