// Türkçe koleksiyonlar: Dizi, Dizin, Yöney, Eşlem, Küme, Dizik, EsnekDizik, Kuyruk, Yığın, Aralık.
// Her satır gerekli ile denetlenir; tutmayan satır betiği "kaldı" yapar.
dez d = Dizi(3, 1, 2)
gerekli(d.sıralı == Dizi(1, 2, 3), "sıralı")
gerekli(d.işle(_ * 2).topla == 12, "işle/topla")
gerekli(d.ele(_ > 1).boyu == 2 && d.eleDeğilse(_ > 1) == Dizi(1), "ele/eleDeğilse")
gerekli(d.tersi.başı == 2 && d.sonu == 2 && d.kuyruğu == Dizi(1, 2), "tersi/başı/sonu/kuyruğu")
gerekli(d.içeriyorMu(3) && !d.içeriyorMu(9), "içeriyorMu")
gerekli(d.enİrisi == 3 && d.enUfağı == 1, "enİrisi/enUfağı")
gerekli(d.soldanKatla(0)(_ + _) == 6 && d.indirge(_ + _) == 6, "soldanKatla/indirge")
gerekli(d.ikileSırayla.boyu == 3 && d.ikile(Dizi("a", "b", "c")).başı == (3, "a"), "ikile")
gerekli(Dizi(Dizi(1), Dizi(2, 3)).düzİşle(x => x).boyu == 3, "düzİşle")
gerekli(d.öbekle(_ % 2).boyu == 2 && d.böl(_ > 1)._1 == Dizi(3, 2), "öbekle/böl")
gerekli(d.varMı(_ == 3) && d.hepsiİçinDoğruMu(_ > 0) && d.say(_ > 1) == 2, "varMı/hepsiİçinDoğruMu/say")
gerekli(Dizi(1, 1, 2).yinelemesiz == Dizi(1, 2) && d.sırası(2) == 2 && d.dizine == Dizin(3, 1, 2), "yinelemesiz/sırası/dizine")
gerekli(d.doluMu && Dizi[Sayı]().boşMu && d.yazıYap(",") == "3,1,2", "doluMu/boşMu/yazıYap")
dez dn = Dizin(1, 2, 3, 4)
gerekli(dn.al(2) == Dizin(1, 2) && dn.düşür(2) == Dizin(3, 4) && dn.dilim(1, 3) == Dizin(2, 3), "al/düşür/dilim")
gerekli(dn.alDoğruKaldıkça(_ < 3) == Dizin(1, 2) && dn.düşürDoğruKaldıkça(_ < 3) == Dizin(3, 4), "alDoğruKaldıkça")
gerekli((0 :: dn).başı == 0 && dn.öbekli(2).boyu == 2, "ekleme/öbekli")
dez y = Yöney(1, 2, 3)
gerekli(y.güncellenmiş(0, 9).başı == 9 && y.çarp == 6, "Yöney güncellenmiş/çarp")
dez e = Eşlem("a" -> 1, "b" -> 2)
gerekli(e("a") == 1 && e.al("b") == Biri(2) && e.alYoksa("z", 0) == 0 && e.al("z").yokMu, "Eşlem al")
e.eşEkle("c" -> 3); e += ("d" -> 4)
gerekli(e.boyu == 4 && e.içeriyorMu("b") && e.anahtarKümesi == Küme("a", "b", "c", "d"), "Eşlem ekleme/anahtarlar")
gerekli(e.değerler.toList.sum == 10, "Eşlem değerler (a..d eklendikten sonra): " + e.değerler.toList)
dez e10 = e.işle { durum (k, v) => (k, v * 10) }
gerekli(e10.getOrElse("b", -1) == 20, "Eşlem işle: " + e10)
dez k = Küme(1, 2, 2, 3)
gerekli(k.boyu == 3 && k.içeriyorMu(2), "Küme")
gerekli(k.bileşim(Küme(4)).boyu == 4 && k.kesişim(Küme(2, 9)) == Küme(2) && k.fark(Küme(1)) == Küme(2, 3), "küme işlemleri")
dez dz = Dizik(1, 2, 3)
gerekli(dz.boyu == 3 && dz.sonu == 3 && dz.işle(_ + 1).topla == 9, "Dizik")
dez ed = EsnekDizik(1, 2); ed += 3
gerekli(ed.boyu == 3 && EsnekDizik.diziden(dz).boyu == 3, "EsnekDizik")
dez ku = Kuyruk(1, 2); ku.ekle(3)
gerekli(ku.çıkar() == 1 && ku.boyu == 2, "Kuyruk")
dez yg = Yığın(1); yg.koy(2)
gerekli(yg.tepesi == 2 && yg.çek() == 2 && yg.boyu == 1, "Yığın")
gerekli((1 |-| 5).toList.sum == 15 && (1 |- 5).boyu == 4, "aralıklar")
gerekli(rastgeleKarıştır(Dizin(1, 2, 3)).boyu == 3 && rastgeleDiziden(Dizi(7)) == 7, "rastgele")
dez mk = MiskinDizin.sayalım(1)
gerekli(mk.head == 1 && mk.take(3).toList == List(1, 2, 3) && MiskinDizin.doldur(2)(7).toList == List(7, 7), "miskin dizin")
satıryaz("TAMAM: koleksiyonlar")
